liveness-server:
  enable: true
  host: 10.30.21.123
  port: 9082
  secure: true
  ssl:
    enable: false
    client-cert:
      need: false

image:
  is-save-image: true
  folder:
    path: C:\Users\HiepND\Pictures\testImages\
    path-fake-image: D:\MKG\test\fake\
    path-error-image: D:\MKG\test\error\

server:
  port: 8081

nThread : 10
